Resolve #5 -- Add repository setup instructions
Thermondo/django-package-template pull request #33
Opened 2018-10-02 13:51 UTC by codingjoe

2018-10-04 09:40 UTC, Ashlett requested changes
It's a nice idea to also automate creating the package and sending it to GitHub in 1 step :+1: I was wondering if this is the right way to go, but in the end I think the pros outweigh the cons.

If you're adding a distinction between public and private package, maybe you can go 1 step further and make their `README` files different. The public one would contain what it currently contains. The private would have instructions how to install a private package (you can use those which are currently in `README` of the template, I also said in a comment that maybe that's where they belong). Here is a section of `cookiecutter` docs that says you can use `if` in the template similar to Jinja2 syntax: https://cookiecutter.readthedocs.io/en/latest/advanced/choice_variables.html

2018-10-04 12:29 UTC, codingjoe commented on cookiecutter.json
> +    "package_description": "A package that does one thing and does it well.",
good catch, thx!

2018-10-04 12:39 UTC, codingjoe commented on README.md
> +### Private packages
Good idea, that is possible, I will move it.

2018-10-04 15:38 UTC, Ashlett requested changes

2018-10-04 15:38 UTC, Ashlett commented on {{cookiecutter.project_slug}}/README.md
> +-e git+https://GITHUB_TOKEN@github.com/Thermondo/REPO_NAME.git@VERSION_TAG#egg=PACKAGE_NAME
You can replace `REPO_NAME` and `PACKAGE_NAME` with `{{ cookiecutter.project_slug }}`

2018-10-04 15:38 UTC, Ashlett commented on {{cookiecutter.project_slug}}/README.md
> +PACKAGE_NAME = {git = "https://GITHUB_TOKEN@github.com/Thermondo/thermondo-salesforce.git", ref = "VERSION_TAG"}
`thermondo-salesforce` -> `{{ cookiecutter.project_slug }}`
`PACKAGE_NAME` -> `{{ cookiecutter.project_slug }}`

2018-10-05 08:35 UTC, Ashlett approved these changes
LGTM! :tada: thanks for finishing this up!

2018-10-05 08:35 UTC, merged